#!/bin/bash

# test-integer2: evaluate the value of an integer.

INT=-5

if [[ "$INT" =~ ^-?[0-9]+$ ]]; then
	if [ "$INT" -eq 0 ]; then
		echo "INT é zero."
	else
		if [ "$INT" -lt 0 ]; then
			echo "INT is negative."
		else
			echo "INT é positivo."
		fi
		if [ $((INT % 2)) -eq 0 ]; then
			echo "INT is even."
		else
			echo "INT is odd."
		fi
	fi
else
	echo "INT não é um inteiro." >&2
	exit 1
fi
