#!/bin/bash

# test-integer: evaluate the value of an integer.

INT=-5

if [ -z "$INT" ]; then
	echo "INT é vazio." >&2
	exit 1
fi

if [ "$INT" -eq 0 ]; then
	echo "INT é zero."
else
	if [ "$INT" -lt 0 ]; then
		echo "INT é negativo."
	else
		echo "INT é positivo."
	fi
	if [ $((INT % 2)) -eq 0 ]; then
		echo "INT é even."
	else
		echo "INT é odd."
	fi
fi
